os:
  - linux

sudo: required

services:
  - docker

language: go

go:
  - tip
  - 1.8
  - 1.7

script:
  - ./check.sh

notifications:
  email:
    - tiago.katcipis@neoway.com.br
    - matheus.vill@neoway.com.br
    - kamila.hinckel@neoway.com.br
    - leonardo.borges@neoway.com.br
